noc:
  dimension: 4
  numberOfVC: 6
  VCBufferSize: 10
  arbitration: 'RR' # RR / PRIORITY_PREEMPT / PRIORITY_NON_PREEMPT

quantum:
  1: 2
  2: 3
  3: 2
  4: 5
  5: 3
  6: 3
#  7: 1
#  8: 1
#  9: 1
#  10: 1
#  11: 1
#  12: 1
#  13: 1
#  14: 1
#  15: 1
#  16: 1
#  17: 1
#  18: 1
#  19: 1
#  20: 1