noc:
  dimension: 4
  numberOfVC: 4
  VCBufferSize: 4
  arbitration: 'RR' # RR / PRIORITY_PREEMPT / PRIORITY_FIX

quantum:
  1: 3
  2: 3
  3: 3
  4: 3
#  5: 1
#  6: 1
#  7: 1
#  8: 1
#  9: 1
#  10: 1
#  11: 1
#  12: 1
#  13: 1
#  14: 1
#  15: 1
#  16: 1
#  17: 1
#  18: 1
#  19: 1
#  20: 1